language: c

sudo: false

cache:
  directories:
    - $HOME/.cabal/packages
    - $HOME/.cabal/bin
    - $HOME/.cabal/lib

before_cache:
  - rm -f $HOME/.cabal/packages/*/build-reports.log
  - rm -f $HOME/.cabal/packages/*/00-index.cache
  - rm -f $HOME/.cabal/packages/*/00-index.tar

matrix:
  fast_finish: true
  include:
    - env: CABALVER=1.18 GHCVER=7.8.4 HAPPYVER=1.19.4 ALEXVER=3.1.3
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4,happy-1.19.4,alex-3.1.3], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.1 HAPPYVER=1.19.4 ALEXVER=3.1.3
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1,happy-1.19.4,alex-3.1.3], sources: [hvr-ghc]}}
    - env: CABALVER=head GHCVER=head HAPPYVER=1.19.4 ALEXVER=3.1.3
      addons: {apt: {packages: [cabal-install-head,ghc-head,happy-1.19.4,alex-3.1.3], sources: [hvr-ghc]}}
  allow_failures:
  - env: CABALVER=head GHCVER=head

before_install:
  - CABALARGS=""
  - if [ "x$GHCVER" = "xhead" ] ; then CABALARGS=--allow-newer ; fi
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/$HAPPYVER/bin:/opt/alex/$ALEXVER/bin:$HOME/.cabal/bin:$PATH
  - |
    mkdir $HOME/.cabal
    echo 'remote-repo: hackage.haskell.org:http://hackage.fpcomplete.com/' > $HOME/.cab>
    echo 'remote-repo-cache: $HOME/.cabal/packages' >> $HOME/.cabal/config
    if [ "$CABALVER" != "1.16" ]
    then
      echo 'jobs: $ncpus' >> $HOME/.cabal/config
    fi

install:
  - |
    set -ex
    travis_retry cabal update
    travis_retry cabal install c2hs
    cabal install --only-dependencies --enable-tests --enable-benchmarks --ghc-options=-O0 --reorder-goals --max-backjumps=-1 $CABALARGS
    set +ex

script:
  - |
    set -ex
    cabal configure --enable-tests --enable-benchmarks --ghc-options=-O0 --reorder-goals --max-backjumps=-1 $CABALARGS
    cabal check
    cabal test
    cabal sdist && cabal install --force-reinstalls dist/vimus-*.tar.gz
    vimus --version
    set +ex
