language: objective-c

install:
    - echo noop

script:
    - brew update
    - brew install ghc
    - brew install cabal-install
    - brew install homebrew/dupes/ncurses
    - brew link homebrew/dupes/ncurses --force
    - cabal update
    - cabal install alex
    - cabal install happy
    - cabal install c2hs
    - cabal install cpphs
    - (cd ncursesw && cabal install --extra-include-dirs=/usr/include/ncursesw)
    - git clone https://github.com/vimus/libmpd-haskell
    - (cd libmpd-haskell && cabal install)
    - cabal test
    - cabal install
